import Categories from "./components/Categories";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "News App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black`}>
        <Navbar />
        <main className="flex justify-center items-center">
          <div className="container">
            <Categories />
          </div>
        </main>
        {children}
      </body>
    </html>
  );
}
